# Generated by Django 4.1.3 on 2022-12-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_place_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='des',
            field=models.TextField(),
        ),
    ]
