# Generated by Django 4.1.3 on 2022-12-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_place_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='wb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.TextField()),
            ],
        ),
    ]
