# Generated by Django 4.1.3 on 2022-12-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_wb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wb',
            old_name='des',
            new_name='Des',
        ),
        migrations.RenameField(
            model_name='wb',
            old_name='name',
            new_name='Name',
        ),
    ]
