# Generated by Django 4.1.3 on 2023-01-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_dctn_delete_wb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dctn',
        ),
    ]
