# Generated by Django 4.1.3 on 2023-01-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_place_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='activity1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='activity2',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='activity3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='activity4',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='price',
            field=models.IntegerField(),
        ),
    ]
